SELECT 
    CASE
        WHEN GRADES.GRADE >= 8 THEN STUDENTS.NAME
        ELSE NULL
    END AS Name,
    GRADES.GRADE,
    STUDENTS.MARKS
FROM 
    GRADES
JOIN 
    STUDENTS ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY 
    GRADES.GRADE DESC,
    CASE
        WHEN GRADES.GRADE >= 8 THEN STUDENTS.NAME
        ELSE CAST(STUDENTS.MARKS AS VARCHAR)
    END;
